config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :bookings
  resources :rooms, only: %i[index show]
  resources :reviews, only: %i[index show create]

  namespace :admin do
    resources :bookings, only: %i[index show update destroy]
    resources :reviews
    resources :rooms
    root 'pages#index'
    post 'rooms/:id', controller: 'rooms', action: :update
  end
  root 'pages#index'
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :bookings
  has_many_attached :images
  validates :room_name, :long_description, :short_description, :price, presence: true

  def images_as_thumbnails(image)
    return unless image.content_type.in?(%w[image/jpg image/jpeg image/png])

    image.variant(resize_to_limit: [400, 200]).processed
  end

  def status
    bookings.each do |booking|
      return true if (booking.move_in..booking.move_out).cover?(Date.today)
    end
    false
  end

  def active_bookings
    bookings.where("move_out > ?", Date.today)
  end
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

module Admin
  class RoomsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_room, only: %i[show edit update destroy]
    def index
      @rooms = Room.all.with_attached_images.order(created_at: :desc)
    end

    def show
      @room_photos = @room.images.all
      @bookings = @room.active_bookings.where(accepted: true)
    end

    def new
      @room = Room.new
    end

    def edit; end

    def create
      @room = Room.new(room_params)
      redirect_to admin_rooms_path, notice: 'Комната была создана.' if @room.save
    end

    def update
      if @room.update(room_params)
        flash[:notice] = 'Room was updated.'
        redirect_to admin_rooms_path, notice: 'Комната была обновлена'
      else
        render :edit, status: :bad_request
      end
    end

    def destroy
      Booking.where(room_id: @room.id).each do |booking|
        Booking.destroy(booking.id)
      end
      if @room.destroy
        redirect_to admin_rooms_path
      end
    end

    private

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:room_name, :short_description, :long_description, :price, images: [])
    end
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: %i[show]
  def index
    @rooms = Room.all.with_attached_images.order(created_at: :desc)
  end

  def show
    @booking = Booking.new
    @room.images.all
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/admin/rooms_helper.rb
# frozen_string_literal: true

module Admin
  module RoomsHelper
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/admin/rooms/_form.html.erb
<% if @room.errors.any? %>
  <h2>The following errors prevented the room from saving:</h2>
  <ul>
    <% @room.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div align="center" class="rooms-form">
  <%= form_for :room, url: admin_rooms_url, data: {turbo:false} do |form| %>
    <div>
      <%= form.label 'Название комнаты', style: "display: block" %>
      <%= form.text_field :room_name %>
    </div>

    <div>
      <%= form.label "Подробное описание", style: "display: block" %>
      <%= form.text_area :long_description %>
    </div>

    <div>
      <%= form.label "Описание", style: "display: block" %>
      <%= form.text_area :short_description %>
    </div>


    <div>
      <%= form.label "Цена", style: "display: block" %>
      <%= form.number_field :price %>
    </div>
    <br>
    <div>
      <%= form.label "Добавить изображение:", style: "display: block" %>
      <%= form.file_field :images, multiple: true %><br>
    </div>
    <br>
    <div>
      <%= form.submit "Сохранить" %>
    </div>

  <% end %>
</div>

app/views/admin/rooms/_form_edit.html.erb
<% if @room.errors.any? %>
  <h2>The following errors prevented the room from saving:</h2>
  <ul>
    <% @room.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div align="center" class="rooms-form">
  <%= form_for :room, url: admin_room_path, data: {turbo:false} do |form| %>
  <div>
    <%= form.label 'Название комнаты', style: "display: block" %>
    <%= form.text_field :room_name %>
  </div>

  <div>
    <%= form.label "Подробное описание", style: "display: block" %>
    <%= form.text_area :long_description %>
  </div>

  <div>
    <%= form.label "Описание", style: "display: block" %>
    <%= form.text_area :short_description %>
  </div>


  <div>
    <%= form.label "Цена", style: "display: block" %>
    <%= form.number_field :price %>
  </div>
  <br>
  <div>
    <%= form.label "Добавить изображение:", style: "display: block" %>
    <% room.images.each do |image|%>
      <%= link_to image_tag(room.images_as_thumbnails(image)), image %>
    <%end%>
  </div>
  <div>
    <%= form.file_field :images, multiple: true %><br>
  </div>
  <br>
  <div>
    <%= form.submit "Сохранить" %>
  </div>

<% end %>
</div>

app/views/admin/rooms/_room.html.erb
<%= render 'admin/layouts/navigation' %>

<div align="center" class="rooms-form">
  <div id="<%= dom_id room %>">
    <td>
      <p><strong>номер комнаты: </strong>
        <%= room.id %></p>
    <p> <strong>название комнаты: </strong>
      <%= room.room_name %></p>
    <p> <strong>создана: </strong>
      <%= room.created_at %></p>
    <p> <strong>обновлена: </strong>
      <%= room.updated_at %></p>
    <p> <strong>статус: </strong>
      <% if room.status%>
        <span style="color: red"> занята </span>
      <% else %>
        <span style="color: green"> свободна </span>
      <% end %>
    </p>
  </td>

    <b>Активные брони: </b>
    <table align="center">
      <tr>
        <th>Имя</th>
        <th>email</th>
        <th>Дата заезда</th>
        <th>Дата выезда</th>
      </tr>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.name %></td>
          <td><%= booking.email %></td>
          <td><%= booking.move_in %></td>
          <td><%= booking.move_out %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <p> <%= button_to "Редактировать", edit_admin_room_path(room), method: :get %> </p>
  <p> <%= button_to "Удалить", admin_room_path(room), method: :delete, data: { confirm: "Вы уыерены, что хотите удалить эту комнату?" } %></p>

</div>

app/views/admin/rooms/edit.html.erb
<%= render 'admin/layouts/navigation' %>

<h1 align="center">Редактирование комнаты</h1>
<%= render 'form_edit', room: @room %>
<div align="center">
  <%= link_to "К списку комнат", admin_rooms_url %>
</div>

app/views/admin/rooms/index.html.erb
<%= render 'admin/layouts/navigation' %>

<h1 align="center">Список комнат</h1>
<p align="center"><%= link_to "Добавить комнату", new_admin_room_path %></p>
<br>
<table border="2" align="center">
  <tr>
    <th>Номер комнаты</th>
    <th>Название комнаты</th>
    <th>Создана</th>
    <th>Отредактирована</th>
    <th>Статус</th>
  </tr>
  <% @rooms.each do |admin_room| %>
    <tr>
      <td><%= admin_room.id %></td>
      <td><%= admin_room.room_name %></td>
      <td><%= admin_room.created_at %></td>
      <td><%= admin_room.updated_at %></td>
      <td>
        <% if admin_room.status%>
          <span style="color: red"> занята </span>
        <% else %>
          <span style="color: green"> свободна </span>
        <% end %>
      </td>
      <td>
      <%= button_to "Редактировать", edit_admin_room_path(admin_room), method: :get %></td>
      <td><%= button_to "Показать", admin_room_path(admin_room), method: :get %></td>
      <td><%= button_to "Удалить", admin_room_path(admin_room), method: :delete %></td>

    </tr>
  <% end %>
</table>

app/views/admin/rooms/new.html.erb
<%= render 'admin/layouts/navigation' %>

<h1 align="center">Добавление комнаты</h1>
<%= render 'form' , room: @room %>
<div align="center">
  <%= link_to "К списку комнат", admin_rooms_url %>
</div>

app/views/admin/rooms/show.html.erb
<%= render @room %>
<div align="center">
  <%= link_to "К списку комнат", admin_rooms_url %>
</div>