config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :bookings
  resources :rooms, only: %i[index show]
  resources :reviews, only: %i[index show create]

  namespace :admin do
    resources :bookings, only: %i[index show update destroy]
    resources :reviews
    resources :rooms
    root 'pages#index'
    post 'rooms/:id', controller: 'rooms', action: :update
  end
  root 'pages#index'
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

module Admin
  class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_review, only: %i[show update destroy]
    def index
      @reviews = Review.all.order(created_at: :desc)
    end

    def show; end

    def update
      if @review.update(published: true)
        redirect_to admin_reviews_path, notice: 'Отзыв был опубликован'
      end
    end

    def destroy
      @review.destroy
      redirect_to admin_reviews_path, notice: 'Отзыв был удален'
    end

    private

    def set_review
      @review = Review.find(params[:id])
    end
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def index
    @reviews = Review.all.where(published: true).order(created_at: :desc)
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to reviews_path, notice: 'Отзыв был добавлен, его одобряет администратор!'
    else
      @reviews = Review.all.where(published: true).order(created_at: :desc)
      render 'reviews/index'
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :email, :review_text)
  end
end

app/helpers/admin/reviews_helper.rb
# frozen_string_literal: true

module Admin
  module ReviewsHelper
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/admin/reviews/_review.html.erb
<div align="center" id="review">
  <p> <strong>имя: </strong>
    <%= review.name %>
  <strong>| email: </strong>
    <%= review.email %>
  </p>

  <p> <strong>отзыв: </strong>
    <%= review.review_text %>
  </p>

  <strong>опубликовано: </strong>
  <% if review.published %>
    <span style="color: green;"><%= "да" %></span>
  <% else %>
    <span style="color: red;"><%= "нет" %></span>
  <% end %>
  </p>

  <p>
    <% unless review.published %>
      <%= button_to "Опубликовать отзыв", admin_review_path(review), method: :put, class: 'btn btn-success' %>
    <% end %>
    <%= button_to "Удалить отзыв", admin_review_path(review), method: :delete, class: 'btn btn-danger' %>
  </p>
</div>

app/views/admin/reviews/index.html.erb
<%= render 'admin/layouts/navigation' %>
<h1 align="center">Список отзывов</h1>
<br>
<% @reviews.each do |review| %>
  <%= render review %>
<% end %>

app/views/admin/reviews/show.html.erb
<%= render @review %>