config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :bookings
  resources :rooms, only: %i[index show]
  resources :reviews, only: %i[index show create]

  namespace :admin do
    resources :bookings, only: %i[index show update destroy]
    resources :reviews
    resources :rooms
    root 'pages#index'
    post 'rooms/:id', controller: 'rooms', action: :update
  end
  root 'pages#index'
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :room
  validates :move_in, :move_out, presence: true
end

app/controllers/admin/bookings_controller.rb
# frozen_string_literal: true

module Admin
  class BookingsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_booking, only: %i[show edit update destroy]

    def index
      @bookings = Booking.where("move_out > ?", Date.today).order(created_at: :desc)
      respond_to do |format|
        format.html { render status: :ok }
        format.csv do
          send_data ExportBookingsCsvJob.perform_later,
                    filename: 'bookings.csv'
        end
        format.xlsx do
          send_data ExportBookingsCsvJob.perform_later,
                    filename: 'bookings.xlsx'
        end
      end
    end

    def show
      @room = @booking.room
    end

    def update
      if @booking.update(accepted: true)
        BookingMailer.with(booking: @booking).booking_approved.deliver_now
        redirect_to admin_bookings_path, notice: 'Бронь обновлена'
      end
    end

    def destroy
      @booking.destroy
      redirect_to admin_bookings_path
    end

    private

    def set_booking
      @booking = Booking.find(params[:id])
    end
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

# Bookings
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all.order(created_at: :desc)
  end

  def show; end

  def new
    @booking = Booking.new
  end

  def edit; end

  def create
    @booking = Booking.new(booking_params)
    redirect_to rooms_url, notice: 'Бронь отправлена на одобрение' if @booking.save
  end

  def destroy
    redirect_to rooms_url if @booking.destroy
  end

  def update
    redirect_to booking_url(@booking) if @booking.update(booking_params)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:name, :email, :move_in, :move_out, :room_id)
  end
end

app/helpers/admin/bookings_helper.rb
# frozen_string_literal: true

module Admin
  module BookingsHelper
  end
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div class="booking" id="<%= dom_id booking %>">
  <p> <strong> имя: </strong>
    <%= booking.name %>
  </p>

  <p> <strong> email: </strong>
    <%= booking.email %>
  </p>

  <p> <strong> заезд: </strong>
    <%= booking.move_in %>
  </p>

  <p> <strong> выезд: </strong>
    <%= booking.move_out %>
  </p>

  <p> <strong> комната: </strong>
    <%= booking.room_id %>
  </p>

</div>

app/views/bookings/_form.html.erb
<% if @booking.errors.any? %>
  <h2>The following errors prevented the article from saving:</h2>
  <ul>
    <% @booking.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div align="center" class="rooms-form">
  <%= form_with model: @booking do |f| %>
    <p>
      <%= f.label "Имя" %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label "Дата заезда" %><br>
      <%= f.date_field :move_in %>
    </p>
    <p>
      <%= f.label "Дата выезда" %><br>
      <%= f.date_field :move_out %>
    </p>
    <p style="display: none">
      <%= f.label :room_id %><br>
      <%= f.number_field :room_id, :value => room_id %>
    </p>

    <p>
      <%= f.submit "Отправить на одобрение" %>
    </p><% end %>
</div>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>
<%= render "form", booking: @booking, room_id: @booking.room_id %>

<p>
  <%= link_to "Показать", @booking %> |
  <%= link_to "К списку комнат", rooms_path %>
</p>

app/views/bookings/index.html.erb
<%= render 'layouts/navigation' %>

<h1 align="center">Список броней</h1>
<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show", booking %>
    </p>
  <% end %>
</div>

<%= link_to "Создать бронь", new_booking_path %>

app/views/bookings/new.html.erb
<h1>Новая бронь</h1>
<%= render "form", booking: @booking %>
<%= link_to "Back to bookings", bookings_path %>

app/views/bookings/show.html.erb
<%= render @booking %>

<p>
  <%= link_to "Изменить бронь", edit_booking_path(@booking) %> |
  <%= link_to "К списку комнат", rooms_path %>
  <%= button_to "Удалить бронь", @booking, method: :delete %>
</p>