config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :bookings
  resources :rooms, only: %i[index show]
  resources :reviews, only: %i[index show create]

  namespace :admin do
    resources :bookings, only: %i[index show update destroy]
    resources :reviews
    resources :rooms
    root 'pages#index'
    post 'rooms/:id', controller: 'rooms', action: :update
  end
  root 'pages#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :room
  validates :move_in, :move_out, presence: true
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  validates :name, :email, :review_text, presence: true
  before_save { self.email = email.downcase }
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :bookings
  has_many_attached :images
  validates :room_name, :long_description, :short_description, :price, presence: true

  def images_as_thumbnails(image)
    return unless image.content_type.in?(%w[image/jpg image/jpeg image/png])

    image.variant(resize_to_limit: [400, 200]).processed
  end

  def status
    bookings.each do |booking|
      return true if (booking.move_in..booking.move_out).cover?(Date.today)
    end
    false
  end

  def active_bookings
    bookings.where("move_out > ?", Date.today)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/pages_controller.rb
# frozen_string_literal: true

module Admin
  class PagesController < ApplicationController
    before_action :authenticate_user!
    def index
      @rooms = Room.all.with_attached_images
    rescue Redis::CannotConnectError # heroku doesn't let redis to work correctly,
      # but this mistake doesn't affect app procedures
      redirect_to root_path
    end
  end
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

module Admin
  class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_review, only: %i[show update destroy]
    def index
      @reviews = Review.all.order(created_at: :desc)
    end

    def show; end

    def update
      if @review.update(published: true)
        redirect_to admin_reviews_path, notice: 'Отзыв был опубликован'
      end
    end

    def destroy
      @review.destroy
      redirect_to admin_reviews_path, notice: 'Отзыв был удален'
    end

    private

    def set_review
      @review = Review.find(params[:id])
    end
  end
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

module Admin
  class RoomsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_room, only: %i[show edit update destroy]
    def index
      @rooms = Room.all.with_attached_images.order(created_at: :desc)
    end

    def show
      @room_photos = @room.images.all
      @bookings = @room.active_bookings.where(accepted: true)
    end

    def new
      @room = Room.new
    end

    def edit; end

    def create
      @room = Room.new(room_params)
      redirect_to admin_rooms_path, notice: 'Комната была создана.' if @room.save
    end

    def update
      if @room.update(room_params)
        flash[:notice] = 'Room was updated.'
        redirect_to admin_rooms_path, notice: 'Комната была обновлена'
      else
        render :edit, status: :bad_request
      end
    end

    def destroy
      Booking.where(room_id: @room.id).each do |booking|
        Booking.destroy(booking.id)
      end
      if @room.destroy
        redirect_to admin_rooms_path
      end
    end

    private

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:room_name, :short_description, :long_description, :price, images: [])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

# Bookings
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all.order(created_at: :desc)
  end

  def show; end

  def new
    @booking = Booking.new
  end

  def edit; end

  def create
    @booking = Booking.new(booking_params)
    redirect_to rooms_url, notice: 'Бронь отправлена на одобрение' if @booking.save
  end

  def destroy
    redirect_to rooms_url if @booking.destroy
  end

  def update
    redirect_to booking_url(@booking) if @booking.update(booking_params)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:name, :email, :move_in, :move_out, :room_id)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  include HTTParty
  def index
    begin
      redirect_to '/admin' if user_signed_in?
      @rooms = Room.all.with_attached_images
    rescue Redis::CannotConnectError # heroku doesn't let redis to work correctly,
      # but this mistake doesn't affect app procedures
      redirect_to root_path
    end
    weather
  end

  private

  def weather
    response = HTTParty.get('http://api.openweathermap.org/data/2.5/group?appid=6726452b30524451234e6dc452d78184&id=498817&units=metric')
    body = JSON.parse(response.body)
    @temp = body['list'][0]['main']['temp']
    @clouds = body['list'][0]['weather'][0]['description']
    @wind = body['list'][0]['wind']['speed']
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def index
    @reviews = Review.all.where(published: true).order(created_at: :desc)
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to reviews_path, notice: 'Отзыв был добавлен, его одобряет администратор!'
    else
      @reviews = Review.all.where(published: true).order(created_at: :desc)
      render 'reviews/index'
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :email, :review_text)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: %i[show]
  def index
    @rooms = Room.all.with_attached_images.order(created_at: :desc)
  end

  def show
    @booking = Booking.new
    @room.images.all
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/admin/bookings_helper.rb
# frozen_string_literal: true

module Admin
  module BookingsHelper
  end
end

app/helpers/admin/reviews_helper.rb
# frozen_string_literal: true

module Admin
  module ReviewsHelper
  end
end

app/helpers/admin/rooms_helper.rb
# frozen_string_literal: true

module Admin
  module RoomsHelper
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def image_tag(source, options = {})
    super(source, options) if source.present?
  end
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/admin/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-dark" style="margin-bottom: 20px;">
  <div class="container-fluid">
    <%= link_to "Главная", '/admin', class: "navbar-brand", id: "logo" %>
    <%= link_to "Комнаты", admin_rooms_path, class: "navbar-brand", id: "logo" %>
    <%= link_to "Отзывы", admin_reviews_path, class: "navbar-brand", id: "logo" %>
    <%= link_to "Брони", admin_bookings_path, class: "navbar-brand", id: "logo" %>
    <%= link_to "Выйти", destroy_user_session_path, :method => :delete, class: "navbar-brand", id: "logo" %>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

app/views/admin/pages/index.html.erb
<%= render 'admin/layouts/navigation' %>

<h1 align="center"> Добро пожаловать, администратор! </h1>

<div align="center" style="margin-bottom: 20px">
  <% @rooms.each do |room|%>
      <% room.images.limit(1).each do |image|%>
      <% if image %>
        <%= link_to image_tag(room.images_as_thumbnails(image)), image %>
      <% end %>
      <%end%>
  <% end %>
</div>

<div align="center">
  <table>
    <tr>
      <td>Количество активных броней</td> <td><%=Booking.where("move_out > ?", Date.today).where(accepted: true).count %></td>
    </tr>
    <tr>
      <td>Количество опубликованных отзывов</td> <td><%=Review.where(published: true).count %></td>
    </tr>
    <tr>
      <td>Количество комнат</td> <td><%=Room.count %></td>
    </tr>
  </table>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-dark" style="margin-bottom: 20px;">
  <div class="container-fluid">
    <%= link_to "Главная", root_path, class: "navbar-brand", id: "logo" %>
    <%= link_to "Комнаты", rooms_path, class: "navbar-brand", id: "logo" %>
    <%= link_to "Отзывы", reviews_path, class: "navbar-brand", id: "logo" %>
    <%= link_to "Войти", 'users/sign_in', class: "navbar-brand", id: "logo" %>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guest house</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <div class="flex-wrapper">
    <div class="body">
    <%= yield %>
    </div>

    <div class="footer">
      <p align="center"> Guest house | 2023 </p>
    </div>
  </div>
</html>

app/views/pages/index.html.erb
<%= render 'layouts/navigation' %>

<h1 align="center"> Добро пожаловать в Guest House </h1>

<div align="center">
  <% @rooms.each do |room|%>
    <% room.images.limit(1).each do |image|%>
      <% if image %>
        <%= link_to image_tag(room.images_as_thumbnails(image)), image %>
      <% end %>
    <%end%>
  <% end %>
</div>
<br> <br>
<div class="info" align="center">
  <div>
    <b>Наше расположение: </b>
    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A5d0861e6033523d3605860f5d872a1b18ea703a5413eb35ad3f147a811c4e6a4&amp;width=548&amp;height=540&amp;lang=ru_RU&amp;scroll=true"></script>
  </div>
  <div>
    <p align="center"> <b> Погода в Санкт-Петербурге: </b> </p>
    <div>
      <table border="2" align="center">
        <tr>
          <td><strong>Температура</strong></td>
          <td><%= @temp %></td>
        </tr>
        <tr>
          <td><strong>Облачность</strong></td>
          <td><%= @clouds %></td>
        </tr>
        <tr>
          <td><strong>Ветер</strong></td>
          <td><%= @wind %></td>
        </tr>
      </table>
    </div>
  </div>
</div>